### ISSUE TITLE
github workflow doesn't work

### ISSUE THREAD

**Issue by umjammer** [umjammer/vavi-sound-sandbox#17]
macos-14 wtf?

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.klab.packetcast.audio.AmplitudeAudioInputStreamTest
2024-02-12 06:29:35,421 [FINE] enter available: 1764044
	at vavi.sound.sampled.alac.AlacAudioFileReader.getAudioFileFormat(AlacAudioFileReader.java:74)
2024-02-12 06:29:35,425 [FINE] error exit available: 1764044
	at vavi.sound.sampled.alac.AlacAudioFileReader.getAudioFileFormat(AlacAudioFileReader.java:79)
2024-02-12 06:29:38,115 [FINE] enter available: 1764044
	at vavi.sound.sampled.alac.AlacAudioFileReader.getAudioFileFormat(AlacAudioFileReader.java:74)
2024-02-12 06:29:38,117 [FINE] error exit available: 1764044
	at vavi.sound.sampled.alac.AlacAudioFileReader.getAudioFileFormat(AlacAudioFileReader.java:79)
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.009 s -- in org.klab.packetcast.audio.AmplitudeAudioInputStreamTest
[INFO] Running MmlTest
Warning:  Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.002 s -- in MmlTest
[INFO] Running vavi.sound.sampled.opus.OpusTest
2024-02-12 06:29:40,144 [INFO] Time was 103ms
	at vavi.sound.sampled.opus.OpusTest.test(OpusTest.java:117)
2024-02-12 06:29:40,144 [INFO] Done!
	at vavi.sound.sampled.opus.OpusTest.test(OpusTest.java:[120](https://github.com/umjammer/vavi-sound-sandbox/actions/runs/7868088543/job/21464741612?pr=16#step:5:121))
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.168 s -- in vavi.sound.sampled.opus.OpusTest
[INFO] Running vavi.sound.sampled.opus.OpusFormatConversionProviderTest
2024-02-12 06:29:40,469 [FINE] enter available: [127](https://github.com/umjammer/vavi-sound-sandbox/actions/runs/7868088543/job/21464741612?pr=16#step:5:128)120
	at vavi.sound.sampled.opus.OpusAudioFileReader.getAudioFileFormat(OpusAudioFileReader.java:72)
2024-02-12 06:29:40,474 [FINE] finally available: 127120
	at vavi.sound.sampled.opus.OpusAudioFileReader.getAudioFileFormat(OpusAudioFileReader.java:93)
2024-02-12 06:29:40,476 [INFO] IN: OPUS 48000.0 Hz, unknown bits per sample, stereo, unknown frame size, unknown frame rate
	at vavi.sound.sampled.opus.OpusFormatConversionProviderTest.test0(OpusFormatConversionProviderTest.java:49)
2024-02-12 06:29:40,477 [INFO] OUT: PCM_SIGNED 48000.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian
	at vavi.sound.sampled.opus.OpusFormatConversionProviderTest.test0(OpusFormatConversionProviderTest.java:56)
2024-02-12 06:29:40,610 [FINE] ★1 info: Rococoa Mixer, version 0.0.1
	at vavi.sound.sampled.rococoa.RococoaMixerProvider.getMixer(RococoaMixerProvider.java:34)
Skipping non audio packet org.gagravarr.opus.OpusInfo@1b45c0e mid audio stream
Skipping non audio packet org.gagravarr.opus.OpusTags@11f0a5a1 mid audio stream
2024-02-12 06:36:41,806 [INFO] Start
	at vavi.sound.sampled.opus.OpusFormatConversionProviderTest.lambda$test0$0(OpusFormatConversionProviderTest.java:64)
Error: The operation was canceled.
```

**Comment by umjammer** [comment]
current version is working
